### ISSUE TITLE
How to setting button background color?

### ISSUE THREAD

**Issue by andarm** [fyne-io/fyne-x#23]
###  I have question about to change button background color.  
- I can not found any demo about the it. 
- I only find these.
- (1) "type ButtonStyle" 
- (2) ButtonStyle determines the behaviour and rendering of a button.  
- I hope you can resolve my confuse , thank you so much.

**Comment by Jacalz** [comment]
I am pretty sure that this is in the wrong issue tracker. Given that plus the answer above, I am going to close this.
