### ISSUE TITLE
Fyne-X Calendar not sizing correctly

### ISSUE THREAD

**Issue by ZerkerEOD** [fyne-io/fyne-x#74]
When the calendar resizes, is seems to render over/under other objects when all in a vbox.

![](https://cdn.discordapp.com/attachments/953030515152281650/1152286458141483149/image.png)

**Comment by ZerkerEOD** [comment]
@andydotxyz, I apologize. I got really busy at work and forgot about checking this. However, today I grabbed the updates to FyneX and reverted my code to the original, and everything appears to be working. Thank you so much for your help and for fixing this.

**Comment by andydotxyz** [comment]
Glad it's all working
