### ISSUE TITLE
bad fileroot even hought setting

### ISSUE THREAD

**Issue by MatejMagat305** [fyne-io/fyne-x#85]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/fyne-io/fyne/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Describe the bug

I set 	`files := xWidget.NewFileTree(app.Storage().RootURI())` ..., maybe it is not bug(in this case i am sorry), but when `create, err := e.app.Storage().Create(strings.Join([]string{entry.Text, ".cl"}, ""))` create dir "Document", why do not  `xWidget` look there?

### How to reproduce

1.    go to https://github.com/MatejMagat305/fyneCL
2.    download it
3.    run multiple go run .
4.    debug on 48th line in file `files.go`

### Screenshots

![path](https://github.com/fyne-io/fyne/assets/61238240/b8a2a7b1-a08a-4028-bce9-6ea09094ad72)

### Example code

```go

	create, err := e.app.Storage().Create(strings.Join([]string{entry.Text, ".cl"}, ""))

....        

	files := xWidget.NewFileTree(ed.app.Storage().RootURI())
```

### Fyne version

fyne.io/fyne/v2 v2.4.4

### Go compiler version

1.22.0

### Operating system and version

Pop!_OS 22.04 LTS x86_64

### Additional Information

it is same code as  fyne-io/fyne#4668, but probably different problem, so I was create next issues ...

**Comment by MatejMagat305** [comment]
ou, sorry,

I was change to:
```go 
	child, err := storage.Child(ed.app.Storage().RootURI(), "Document")
	if err != nil {
		return nil
	}
	files := xWidget.NewFileTree(child)
```
but it not show me files ...

**Comment by andydotxyz** [comment]
I think that "Document" should be "Documents"...

However that is an internal detail, and `Storage.List` will always list the documents you have created.

**Comment by MatejMagat305** [comment]
ach sorry it is my errors with maximaze ....

![max](https://github.com/fyne-io/fyne-x/assets/61238240/29356e0c-24b4-4b60-ab40-ab3327f873b6)

**Comment by andydotxyz** [comment]
So it's working then? 👍

**Comment by MatejMagat305** [comment]
> So it's working then? 👍

yes..., but until now I do not know why Split is render only 1 row hight ...
![0](https://github.com/fyne-io/fyne-x/assets/61238240/dd412fe8-5007-44a6-9308-dcdb93d90f5d)

**Comment by andydotxyz** [comment]
> > So it's working then? 👍
> 
> yes..., but until now I do not know why Split is render only 1 row hight ...

Because you are packing your entire UI into a VBox. The job of a VBox is to make all items minimum height.
