### ISSUE TITLE
[q] Is a form of more in-depth theming supported?

### ISSUE THREAD

**Issue by xplshn** [fyne-io/fyne-x#94]
Hi, awesome work, I just wanted to ask something; would it be possible to style `fyne` to look like SerenityOS' libUI? Or like MacOS Leopard? Where should I start if I want to radically change the way `fyne` looks? The adwaita theme does not change how the buttons are styled, it only changes colors and some SVGs

**Comment by andydotxyz** [comment]
Fyne supports only theming not skinning. That means that you can change lots of aspects of the UI, but you cannot simply replace widgets with other images or visuals.

Button radius, shadows etc can all be themed so a lot is possible. Without a more specific questions it is hard to answer definitively.

**Comment by xplshn** [comment]
Hmm, are gradients supported too?
I wanted to know if it'd be possible to produce fyne programs that look like this:
![image](https://github.com/user-attachments/assets/f3d62910-d9b2-4705-9c7f-576464014594)

**Comment by andydotxyz** [comment]
You can add gradients to your app, in addition to the widgets or by extending existing ones.
Adding gradients where they don't exist using the theme is not supported.

**Comment by xplshn** [comment]
Thanks for the insight
